// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSvIEqqoScBhvKeHy8U90bafGDD2CZMQ4',
    appId: '1:1077647994525:web:dbe559db8e5eb8dd046e74',
    messagingSenderId: '1077647994525',
    projectId: 'chocomil-movies-app-bv',
    authDomain: 'chocomil-movies-app-bv.firebaseapp.com',
    storageBucket: 'chocomil-movies-app-bv.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRXQDY8r1f7_luvCIfLBXHFXGDf9N2X0c',
    appId: '1:1077647994525:android:470b2aed2fe379b2046e74',
    messagingSenderId: '1077647994525',
    projectId: 'chocomil-movies-app-bv',
    storageBucket: 'chocomil-movies-app-bv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1C89Oan59oOHnDbDh6SV4RdBvMf2lx34',
    appId: '1:1077647994525:ios:f4caafd12255d8d2046e74',
    messagingSenderId: '1077647994525',
    projectId: 'chocomil-movies-app-bv',
    storageBucket: 'chocomil-movies-app-bv.firebasestorage.app',
    iosBundleId: 'com.example.chocomil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1C89Oan59oOHnDbDh6SV4RdBvMf2lx34',
    appId: '1:1077647994525:ios:f4caafd12255d8d2046e74',
    messagingSenderId: '1077647994525',
    projectId: 'chocomil-movies-app-bv',
    storageBucket: 'chocomil-movies-app-bv.firebasestorage.app',
    iosBundleId: 'com.example.chocomil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSvIEqqoScBhvKeHy8U90bafGDD2CZMQ4',
    appId: '1:1077647994525:web:a0ff1dcfb46020de046e74',
    messagingSenderId: '1077647994525',
    projectId: 'chocomil-movies-app-bv',
    authDomain: 'chocomil-movies-app-bv.firebaseapp.com',
    storageBucket: 'chocomil-movies-app-bv.firebasestorage.app',
  );
}
